### PR TITLE
Loosen Rails dependencies so that minor versions of 7.1 match

### PR DESCRIPTION
**Pull request by mikeastock**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by dmytro-savochkin — COMMENTED** [review]
Oh, right. 
Can I ask you to change it from `<= 7.2` to `< 7.2` though?

**Comment by mikeastock** [comment]
@dmytro-savochkin done

**Comment by dmytro-savochkin** [comment]
> @dmytro-savochkin done

Thank you!

**Comment by dmytro-savochkin** [comment]
Released this as 4.1.1

**Pull request merged**
