### PR TITLE
Add Rails 7.1 support

### PR DESCRIPTION
**Pull request by gregg-platogo**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ordinathorreur** [comment]
Does this gem really *need* an upper bound Rails point version dependency? If so, perhaps Rails 8 might be a better choice?

**Comment by gregg-platogo** [comment]
> Does this gem really _need_ an upper bound Rails point version dependency? If so, perhaps Rails 8 might be a better choice?

Good point! I didn't know what's the convention/policy for this repo but making it lower than Rails 8 makes much more sense 😉

**Comment by dmytro-savochkin** [comment]
I think it does need an upper-bound because this gem fully depends on ActiveRecord. 
Even now with 7.1, as I've just checked in my fork, it fails the CI with
```
Failures:

  1) Temping.create with a custom parent class uses the provided parent class option
     Failure/Error: connection.create_table(table_name, **DEFAULT_OPTIONS.merge(options))

     ArgumentError:
       Unknown key: :parent_class. Valid keys are: :temporary, :if_not_exists, :options, :as, :comment, :charset, :collation, :rename, :limit, :default, :precision
```
I didn't expect this fail because seemingly there were no big changes in ActiveRecord. 
Gonna take a look at this later today.

But in any case I do think this PR should be to add `<= 7.1`, not `< 8.0`. The breaking changes are not that rare turns out: it broke now with 7.1, previously it also broke with 7.0.

**Comment by dmytro-savochkin** [comment]
Okay, I am gonna merge this and adjust to `<= 7.1` in a separate PR.

Thanks for the PR and also for letting me know Rails 7.1 has been released, I completely missed that 😆

**Pull request merged**
