### PR TITLE
Allow a non-AR specific custom parent class

### PR DESCRIPTION
**Pull request by jetaggart**
Currently, we have some custom superclasses for some of our domain. I wanted to see what you think of this change. I can add tests if you like it and want to incorporate it.

### CODE REVIEW

**Comment by kitop** [comment]
This is a nice feature!

Can you add some documentation to the README?

Happy to add it, but needs to be documented. An example use case would be super helpful too.

Thanks a lot!!

**Comment by kitop** [comment]
Oh, and some tests too, yes :)

**Comment by jetaggart** [comment]
Will do, just wanted to check first before putting more effort in!

On Tue, Oct 11, 2016 at 3:34 AM, Esteban Pastorino <notifications@github.com

**Comment by kitop** [comment]
Great, thanks!!

**Comment by kitop** [comment]
@jetaggart just checking, have you had any time to work on the Readme?

**Comment by kitop** [comment]
Closed in favor of #53

**Pull request closed without merging**
